name: Publish

on:
  push:
    branches:
      - master

jobs:
  publish:
    name: Create a GitHub Release & Upload to PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - uses: relekang/python-semantic-release@v7.16.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pypi_token: ${{ secrets.PYPI_TOKEN }}
